export const FETCH_ENTITY_QUEUE_DATA = 'FETCH_ENTITY_QUEUE_DATA'
export const FETCH_ENTITY_QUEUE_SUCCESS = 'FETCH_ENTITY_QUEUE_SUCCESS'
export const FETCH_ENTITY_QUEUE_FAILED = 'FETCH_ENTITY_QUEUE_FAILED'
