export const FETCH_ALL_SITE_CATEGORIES = 'FETCH_ALL_SITE_CATEGORIES';
export const FETCH_ALL_SITE_CATEGORIES_SUCCESS = 'FETCH_ALL_SITE_CATEGORIES_SUCCESS';
export const FETCH_ALL_SITE_CATEGORIES_ERROR = 'FETCH_ALL_SITE_CATEGORIES_ERROR';

export const SEND_SELECTED_TOPIC = 'SEND_SELECTED_TOPIC';
export const SEND_SELECTED_TOPIC_SUCCESS = 'SEND_SELECTED_TOPIC_SUCCESS';
export const SEND_SELECTED_TOPIC_ERROR = 'SEND_SELECTED_TOPIC_ERROR';