export const FETCH_ALL_SITE_CATEGORIES = 'FETCH_ALL_SITE_CATEGORIES';
export const FETCH_ALL_SITE_CATEGORIES_SUCCESS = 'FETCH_ALL_SITE_CATEGORIES_SUCCESS';
export const FETCH_ALL_SITE_CATEGORIES_ERROR = 'FETCH_ALL_SITE_CATEGORIES_ERROR';

export const SEND_SELECTED_TOPIC = 'SEND_SELECTED_TOPIC';
export const SEND_SELECTED_TOPIC_SUCCESS = 'SEND_SELECTED_TOPIC_SUCCESS';
export const SEND_SELECTED_TOPIC_ERROR = 'SEND_SELECTED_TOPIC_ERROR';

export const GET_SELECTED_TOPICS = 'GET_SELECTED_TOPICS';
export const GET_SELECTED_TOPICS_SUCCESS = 'GET_SELECTED_TOPICS_SUCCESS';
export const GET_SELECTED_TOPICS_ERROR = 'GET_SELECTED_TOPICS_ERROR';

export const EMPTY_SELECTED_TOPICS_INFO = 'EMPTY_SELECTED_TOPICS_INFO';
export const EMPTY_SEND_TOPICS_INFO = 'EMPTY_SEND_TOPICS_INFO';

export const DESELECT_ALL_TOPICS_INFO = 'DESELECT_ALL_TOPICS_INFO';
