export const FETCH_ALL_SITE_CATEGORIES = 'FETCH_ALL_SITE_CATEGORIES';
export const FETCH_ALL_SITE_CATEGORIES_SUCCESS = 'FETCH_ALL_SITE_CATEGORIES_SUCCESS';
export const FETCH_ALL_SITE_CATEGORIES_ERROR = 'FETCH_ALL_SITE_CATEGORIES_ERROR';