//HeroList
export const REQUEST_HERO_LIST_DATA = 'REQUEST_HERO_LIST_DATA';
export const REQUEST_HERO_LIST_SUCCESS = 'REQUEST_HERO_LIST_SUCCESS';
export const REQUEST_HERO_LIST_FAILED = 'REQUEST_HERO_LIST_FAILED';

//TopList
export const REQUEST_TOP_LIST_DATA = 'REQUEST_TOP_LIST_DATA';
export const REQUEST_TOP_LIST_SUCCESS = 'REQUEST_TOP_LIST_SUCCESS';
export const REQUEST_TOP_LIST_FAILED = 'REQUEST_TOp_LIST_FAILED';

//Bottom List
export const REQUEST_BOTTOM_LIST_DATA = 'REQUEST_BOTTOM_LIST_DATA';
export const REQUEST_BOTTOM_LIST_SUCCESS = 'REQUEST_BOTTOM_LIST_SUCCESS';
export const REQUEST_BOTTOM_LIST_FAILED = 'REQUEST_BOTTOM_LIST_FAILED';

export const EMPTY_ALL_LIST = 'EMPTY_ALL_LIST';
