export const FETCH_OPINIONS = 'FETCH_OPINIONS';
export const FETCH_OPINIONS_SUCCESS = 'FETCH_OPINIONS_SUCCESS';
export const FETCH_OPINIONS_ERROR = 'FETCH_OPINIONS_ERROR';

//Single Writer Opinion Info
export const FETCH_WRITER_OPINIONS = 'FETCH_WRITER_OPINIONS';
export const FETCH_WRITER_OPINIONS_SUCCESS = 'FETCH_WRITER_OPINIONS_SUCCESS';
export const FETCH_WRITER_OPINIONS_ERROR = 'FETCH_WRITER_OPINIONS_ERROR';
export const EMPTY_WRITER_OPINION_DATA = 'EMPTY_WRITER_OPINION_DATA'

export const EMPTY_OPINION_DATA = 'EMPTY_OPINION_DATA';

export const STORE_HOME_OPINION_NID = 'STORE_HOME_OPINION_NID';
