export const REGISTER_USER = 'REGISTER_USER';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILED = 'REGISTER_FAILED';
export const SOCIAL_LOGIN_START = 'SOCIAL_LOGIN_START';
export const SOCIAL_LOGIN_END = 'SOCIAL_LOGIN_END';
export const EMPTY_USER_INFO = 'EMPTY_USER_INFO';
