export const FETCH_SECTION_ARTICLES = 'FETCH_SECTION_ARTICLES';
export const FETCH_SECTION_ARTICLES_SUCCESS = 'FETCH_SECTION_ARTICLES_SUCCESS';
export const FETCH_SECTION_ARTICLES_ERROR = 'FETCH_SECTION_ARTICLES_ERROR';
export const EMPTY_SECTION_ARTICLES = 'EMPTY_SECTION_ARTICLES';
