export const FETCH_WRITER_DETAIL = 'FETCH_WRITER_DETAIL';
export const FETCH_WRITER_DETAIL_SUCCESS = 'FETCH_WRITER_DETAIL_SUCCESS';
export const FETCH_WRITER_DETAIL_ERROR = 'FETCH_WRITER_DETAIL_ERROR';
export const EMPTY_WRITER_DETAIL = 'EMPTY_WRITER_DETAIL'
