export const FETCH_FAVOURITE_OPINIONS = 'FETCH_FAVOURITE_OPINIONS';
export const FETCH_FAVOURITE_OPINIONS_SUCCESS = 'FETCH_FAVOURITE_OPINIONS_SUCCESS';
export const FETCH_FAVOURITE_OPINIONS_ERROR = 'FETCH_FAVOURITE_OPINIONS_ERROR';
export const FETCH_FAVOURITE_ARTICLES = 'FETCH_FAVOURITE_ARTICLES';
export const FETCH_FAVOURITE_ARTICLES_SUCCESS = 'FETCH_FAVOURITE_ARTICLES_SUCCESS';
export const FETCH_FAVOURITE_ARTICLES_ERROR = 'FETCH_FAVOURITE_ARTICLES_ERROR';
export const EMPTY_ALL_DATA = 'EMPTY_ALL_DATA';
