export const FETCH_PROFILE_USER_DETAILS = 'FETCH_PROFILE_USER_DETAILS';
export const FETCH_PROFILE_USER_DETAILS_SUCCESS = 'FETCH_PROFILE_USER_DETAILS_SUCCESS';
export const FETCH_PROFILE_USER_DETAILS_ERROR = 'FETCH_PROFILE_USER_DETAILS_ERROR';

export const SEND_USER_DETAILS = 'SEND_USER_DETAILS';
export const SEND_USER_DETAILS_SUCCESS = 'SEND_USER_DETAILS_SUCCESS';
export const SEND_USER_DETAILS_ERROR = 'SEND_USER_DETAILS_ERROR';
