export const FETCH_PROFILE_USER_DETAILS = 'FETCH_PROFILE_USER_DETAILS';
export const FETCH_PROFILE_USER_DETAILS_SUCCESS = 'FETCH_PROFILE_USER_DETAILS_SUCCESS';
export const FETCH_PROFILE_USER_DETAILS_ERROR = 'FETCH_PROFILE_USER_DETAILS_ERROR';

export const SEND_USER_DETAILS = 'SEND_USER_DETAILS';
export const SEND_USER_DETAILS_SUCCESS = 'SEND_USER_DETAILS_SUCCESS';
export const SEND_USER_DETAILS_ERROR = 'SEND_USER_DETAILS_ERROR';

export const UPDATE_PROFILE_USER_IMAGE = 'UPDATE_PROFILE_USER_IMAGE';
export const UPDATE_USER_IMAGE_SUCCESS = 'UPDATE_USER_IMAGE_SUCCESS';
export const UPDATE_USER_IMAGE_FAILED = 'UPDATE_USER_IMAGE_FAILED';

export const EMPTY_USER_PROFILE_DATA = 'EMPTY_USER_PROFILE_DATA';
