export const FETCH_ALL_WRITERS = 'FETCH_ALL_WRITERS';
export const FETCH_ALL_WRITERS_SUCCESS = 'FETCH_ALL_WRITERS_SUCCESS';
export const FETCH_ALL_WRITERS_ERROR = 'FETCH_ALL_WRITERS_ERROR';


//Send Selected Author detail
export const SEND_SELECTED_AUTHOR = 'SEND_SELECTED_AUTHOR';
export const SEND_SELECTED_AUTHOR_SUCCESS = 'SEND_SELECTED_AUTHOR_SUCCESS';
export const SEND_SELECTED_AUTHOR_ERROR = 'SEND_SELECTED_AUTHOR_ERROR';
