export const FETCH_ALL_WRITERS = 'FETCH_ALL_WRITERS';
export const FETCH_ALL_WRITERS_SUCCESS = 'FETCH_ALL_WRITERS_SUCCESS';
export const FETCH_ALL_WRITERS_ERROR = 'FETCH_ALL_WRITERS_ERROR';


//Send Selected Author detail
export const SEND_SELECTED_AUTHOR = 'SEND_SELECTED_AUTHOR';
export const SEND_SELECTED_AUTHOR_SUCCESS = 'SEND_SELECTED_AUTHOR_SUCCESS';
export const SEND_SELECTED_AUTHOR_ERROR = 'SEND_SELECTED_AUTHOR_ERROR';

//Get Selected Authors Details
export const GET_SELECTED_AUTHOR = 'GET_SELECTED_AUTHOR';
export const GET_SELECTED_AUTHOR_SUCCESS = 'GET_SELECTED_AUTHOR_SUCCESS';
export const GET_SELECTED_AUTHOR_ERROR = 'GET_SELECTED_AUTHOR_ERROR';

export const EMPTY_SELECTED_AUTHORS_INFO = 'EMPTY_SELECTED_AUTHORS_INFO';
export const EMPTY_SELECTED_AUTHORS = 'EMPTY_SELECTED_AUTHORS';


//Remove Selected Author detail
export const REMOVE_AUTHOR = 'REMOVE_AUTHOR';
export const REMOVE_AUTHOR_SUCCESS = 'REMOVE_AUTHOR_SUCCESS';
export const REMOVE_AUTHOR_ERROR = 'REMOVE_AUTHOR_ERROR';

//To Fetch All Selected Authors Details
export const FETCH_ALL_SELECTED_WRITERS_DETAILS = 'FETCH_ALL_SELECTED_WRITERS_DETAILS';
export const FETCH_ALL_SELECTED_WRITERS_DETAILS_SUCCESSS = 'FETCH_ALL_SELECTED_WRITERS_DETAILS_SUCCESSS';
export const FETCH_ALL_SELECTED_WRITERS_DETAILS_ERROR = 'FETCH_ALL_SELECTED_WRITERS_DETAILS_ERROR';
export const EMPTY_SEND_AUTHOR_INFO = 'EMPTY_SEND_AUTHOR_INFO'
export const DESELECT_ALL_WRITERS = 'DESELECT_ALL_WRITERS';

export const SELECTED_DATA_FROM_ONBOARD = 'SELECTED_DATA_FROM_ONBOARD';
export const EMPTY_SELECTED_WRITERS_DATA_FROM_ONBOARD = 'EMPTY_SELECTED_WRITERS_DATA_FROM_ONBOARD';
