//Ticker and Hero
export const REQUEST_TICKER_HERO_DATA = 'REQUEST_TICKER_HERO_DATA'
export const REQUEST_TICKER_HERO_DATA_SUCCESS = 'REQUEST_TICKER_HERO_DATA_SUCCESS'
export const REQUEST_TICKER_HERO_DATA_FAILED = 'REQUEST_TICKER_HERO_DATA_FAILED'

//HeroList and TopList
export const REQUEST_HERO_AND_TOP_LIST_DATA = 'REQUEST_HERO_AND_TOP_LIST_DATA'
export const REQUEST_HERO_AND_TOP_LIST_SUCCESS = 'REQUEST_HERO_AND_TOP_LIST_SUCCESS'
export const REQUEST_HERO_AND_TOP_LIST_FAILED = 'REQUEST_HERO_AND_TOP_LIST_FAILED'