//Ticker and Hero
export const REQUEST_TICKER_HERO_DATA = 'REQUEST_TICKER_HERO_DATA'
export const REQUEST_TICKER_HERO_DATA_SUCCESS = 'REQUEST_TICKER_HERO_DATA_SUCCESS'
export const REQUEST_TICKER_HERO_DATA_FAILED = 'REQUEST_TICKER_HERO_DATA_FAILED'

//HeroList and TopList
export const REQUEST_HERO_AND_TOP_LIST_DATA = 'REQUEST_HERO_AND_TOP_LIST_DATA'
export const REQUEST_HERO_AND_TOP_LIST_SUCCESS = 'REQUEST_HERO_AND_TOP_LIST_SUCCESS'
export const REQUEST_HERO_AND_TOP_LIST_FAILED = 'REQUEST_HERO_AND_TOP_LIST_FAILED'

//writer opinions
export const REQUEST_OPINION_DATA_SUCCESS = 'REQUEST_OPINION_DATA_SUCCESS'
export const REQUEST_OPINION_LIST_DATA = 'REQUEST_OPINION_LIST_DATA'
export const REQUEST_OPINION_DATA_LIST_FAILED = 'REQUEST_OPINION_DATA_LIST_FAILED'
//Section Combo one
export const REQUEST_SECTION_COMBO_ONE = 'REQUEST_SECTION_COMBO_ONE'
export const REQUEST_SECTION_COMBO_ONE_SUCCESS = 'REQUEST_SECTION_COMBO_ONE_SUCCESS'
export const REQUEST_SECTION_COMBO_ONE_FAILED = 'REQUEST_SECTION_COMBO_ONE_FAILED'

//Section Combo two
export const REQUEST_SECTION_COMBO_TWO = 'REQUEST_SECTION_COMBO_TWO'
export const REQUEST_SECTION_COMBO_TWO_SUCCESS = 'REQUEST_SECTION_COMBO_TWO_SUCCESS'
export const REQUEST_SECTION_COMBO_TWO_FAILED = 'REQUEST_SECTION_COMBO_TWO_FAILED'

//Section Combo three
export const REQUEST_SECTION_COMBO_THREE = 'REQUEST_SECTION_COMBO_THREE'
export const REQUEST_SECTION_COMBO_THREE_SUCCESS = 'REQUEST_SECTION_COMBO_THREE_SUCCESS'
export const REQUEST_SECTION_COMBO_THREE_FAILED = 'REQUEST_SECTION_COMBO_THREE_FAILED'

//Section Combo four
export const REQUEST_SECTION_COMBO_FOUR = 'REQUEST_SECTION_COMBO_FOUR'
export const REQUEST_SECTION_COMBO_FOUR_SUCCESS = 'REQUEST_SECTION_COMBO_FOUR_SUCCESS'
export const REQUEST_SECTION_COMBO_FOUR_FAILED = 'REQUEST_SECTION_COMBO_FOUR_FAILED'

//PodcastHome
export const REQUEST_PODCAST_HOME_DATA_SUCCESS = 'REQUEST_PODCAST_HOME_DATA_SUCCESS';
export const REQUEST_PODCAST_HOME_DATA = 'REQUEST_PODCAST_HOME_DATA';
export const REQUEST_PODCAST_HOME_DATA_FAILED = 'REQUEST_PODCAST_HOME_DATA_FAILED';

//Coverage Widget
export const REQUEST_COVERAGE_BLOCK = 'REQUEST_COVERAGE_BLOCK'
export const REQUEST_COVERAGE_BLOCK_SUCCESS = 'REQUEST_COVERAGE_BLOCK_SUCCESS'
export const REQUEST_COVERAGE_BLOCK_FAILED = 'REQUEST_COVERAGE_BLOCK_FAILED'

export const REQUEST_FEATURED_ARTICLE_BLOCK = 'REQUEST_FEATURED_ARTICLE_BLOCK'
export const REQUEST_FEATURED_ARTICLE_BLOCK_SUCCESS = 'REQUEST_FEATURED_ARTICLE_BLOCK_SUCCESS'
export const REQUEST_FEATURED_ARTICLE_BLOCK_FAILED = 'REQUEST_FEATURED_ARTICLE_BLOCK_FAILED'

export const REQUEST_HORIZONTAL_ARTICLE_BLOCK = 'REQUEST_HORIZONTAL_ARTICLE_BLOCK'
export const REQUEST_HORIZONTAL_ARTICLE_SUCCESS = 'REQUEST_HORIZONTAL_ARTICLE_SUCCESS'
export const REQUEST_HORIZONTAL_ARTICLE_FAILED = 'REQUEST_HORIZONTAL_ARTICLE_FAILED'
//Section Combo five
export const REQUEST_SECTION_COMBO_FIVE = 'REQUEST_SECTION_COMBO_FIVE'
export const REQUEST_SECTION_COMBO_FIVE_SUCCESS = 'REQUEST_SECTION_COMBO_FIVE_SUCCESS'
export const REQUEST_SECTION_COMBO_FIVE_FAILED = 'REQUEST_SECTION_COMBO_FIVE_FAILED'

//Section Combo six
export const REQUEST_SECTION_COMBO_SIX = 'REQUEST_SECTION_COMBO_SIX'
export const REQUEST_SECTION_COMBO_SIX_SUCCESS = 'REQUEST_SECTION_COMBO_SIX_SUCCESS'
export const REQUEST_SECTION_COMBO_SIX_FAILED = 'REQUEST_SECTION_COMBO_SIX_FAILED'

//Section Combo seven
export const REQUEST_SECTION_COMBO_SEVEN = 'REQUEST_SECTION_COMBO_SEVEN'
export const REQUEST_SECTION_COMBO_SEVEN_SUCCESS = 'REQUEST_SECTION_COMBO_SEVEN_SUCCESS'
export const REQUEST_SECTION_COMBO_SEVEN_FAILED = 'REQUEST_SECTION_COMBO_SEVEN_FAILED'

//Section Combo eight
export const REQUEST_SECTION_COMBO_EIGHT = 'REQUEST_SECTION_COMBO_EIGHT'
export const REQUEST_SECTION_COMBO_EIGHT_SUCCESS = 'REQUEST_SECTION_COMBO_EIGHT_SUCCESS'
export const REQUEST_SECTION_COMBO_EIGHT_FAILED = 'REQUEST_SECTION_COMBO_EIGHT_FAILED'

//EditorsChoice
export const REQUEST_EDITORS_CHOICE_DATA_SUCCESS = 'REQUEST_EDITORS_CHOICE_DATA_SUCCESS';
export const REQUEST_EDITORS_CHOICE_DATA = 'REQUEST_EDITORS_CHOICE_DATA';
export const REQUEST_EDITORS_CHOICE_DATA_FAILED = 'REQUEST_EDITORS_CHOICE_DATA_FAILED';

//Spotlight
export const REQUEST_SPOTLIGHT_COMBO = 'REQUEST_SPOTLIGHT_COMBO';
export const REQUEST_SPOTLIGHT_COMBO_SUCCESS = 'REQUEST_SPOTLIGHT_COMBO_SUCCESS';
export const REQUEST_SPOTLIGHT_COMBO_FAILED = 'REQUEST_SPOTLIGHT_COMBO_FAILED';

//Spotlight Article Section
export const REQUEST_SPOTLIGHT_ARTICLE_SECTION_DATA = 'REQUEST_SPOTLIGHT_ARTICLE_SECTION_DATA';
export const REQUEST_SPOTLIGHT_ARTICLE_SECTION_DATA_SUCCESS = 'REQUEST_SPOTLIGHT_ARTICLE_SECTION_DATA_SUCCESS';
export const REQUEST_SPOTLIGHT_ARTICLE_SECTION_DATA_FAILED = 'REQUEST_SPOTLIGHT_ARTICLE_SECTION_DATA_FAILED';

//Info Graphic Block Widget
export const REQUEST_INFO_GRAPHIC_BLOCK = 'REQUEST_INFO_GRAPHIC_BLOCK'
export const REQUEST_INFO_GRAPHIC_BLOCK_SUCCESS = 'REQUEST_INFO_GRAPHIC_BLOCK_SUCCESS'
export const REQUEST_INFO_GRAPHIC_BLOCK_FAILED = 'REQUEST_INFO_GRAPHIC_BLOCK_FAILED'

//Info Graphic Block Widget
export const REQUEST_ARCHIVED_ARTICLE_DATA = 'REQUEST_ARCHIVED_ARTICLE_DATA'
export const REQUEST_ARCHIVED_ARTICLE_DATA_SUCCESS = 'REQUEST_ARCHIVED_ARTICLE_DATA_SUCCESS'
export const REQUEST_ARCHIVED_ARTICLE_DATA_FAILED = 'REQUEST_ARCHIVED_ARTICLE_DATA_FAILED'

export const REQUEST_US_ELECTION_DATA = 'REQUEST_US_ELECTION_DATA'
export const REQUEST_US_ELECTION_DATA_SUCCESS = 'REQUEST_US_ELECTION_DATA_SUCCESS'
export const REQUEST_US_ELECTION_DATA_FAILED = 'REQUEST_US_ELECTION_DATA_FAILED'

export const REQUEST_CONTESTANTS_DATA = 'REQUEST_CONTESTANTS_DATA'
export const REQUEST_CONTESTANTS_DATA_SUCCESS = 'REQUEST_CONTESTANTS_DATA_SUCCESS'
export const REQUEST_CONTESTANTS_DATA_FAILED = 'REQUEST_CONTESTANTS_DATA_FAILED'

