export const SAVE_TOKEN_REQUEST = 'SAVE_TOKEN_REQUEST';
export const SAVE_TOKEN_SUCCESS = 'SAVE_TOKEN_SUCCESS';
export const SAVE_TOKEN_FAILED = 'SAVE_TOKEN_FAILED';

export const SAVE_TOKEN_AFTER_REGISTRATION_REQUEST = 'SAVE_TOKEN_AFTER_REGISTRATION_REQUEST';
export const SAVE_TOKEN_AFTER_REGISTRATION_SUCCESS = 'SAVE_TOKEN_AFTER_REGISTRATION_SUCCESS';
export const SAVE_TOKEN_AFTER_REGISTRATION_FAILED = 'SAVE_TOKEN_AFTER_REGISTRATION_FAILED';
