export enum flatListUniqueKey {
  ARTICLE_SECTION = 'ArticleSection',
  SHORT_ARTICLE = 'shortArticle',
  CAROUSEL_WIDGET = 'carousel',
  STORY_WIDGET = 'StoryWidget',
  AUTHOR_WIDGET = 'AuthorWidget',
  MOST_READ_LIST = 'MostReadList',
  BANNER_ARTICLE_LIST = 'BannerArticleList',
  FOLLOW_FAVORITE_AUTHOR_WIDGET = 'FollowFavoriteAuthorWidget',
  KEEP_NOTIFIED_WIDGET = 'KeepNotifiedWidget',
  RELATED_ARTICLE_WIDGET = 'RelatedArticleWidget',
  OPINION_WRITER_SECTION = 'OpinionWriterSection',
  OPINION_WRITER_ARTICLES_SECTION = 'OpinionWriterArticleSection',
  PODCAST_CARD_SECTION = 'PodcastCardSection',
  MOST_PLAYED_CARD = 'MostPlayedcard',
  LATEST_NEWS_SUMMARY_WIDGET = 'LatestNewsSummarySection',
  EDITORS_PICK_WIDGET = 'EditorPickWidget',
  PODCAST_OPINION_ARTICLE_WIDGET = 'PodcastOpinionArticleSection',
  INTERESTED_TOPICS = 'InterestedTopics',
  NEWS_FEED = 'NewsFeed',
  NEWS_LETTER_WIDGET = 'NewsLetterWidget',
  CONTENT_FOR_YOU = 'ContentForYou',
}
