export const FETCH_VIDEO = 'FETCH_VIDEO';
export const FETCH_VIDEO_SUCCESS = 'FETCH_VIDEO_SUCCESS';
export const FETCH_VIDEO_FAILED = 'FETCH_VIDEO_FAILED';

export const FETCH_VIDEO_PAGINATION = 'FETCH_VIDEO_PAGINATION';
export const FETCH_VIDEO_PAGINATION_SUCCESS = 'FETCH_VIDEO_PAGINATION_SUCCESS';
export const FETCH_VIDEO_PAGINATION_FAILED = 'FETCH_VIDEO_PAGINATION_FAILED';
