//Send Selected Notification
export const SEND_SELECTED_NOTIFICATION = 'SEND_SELECTED_NOTIFICATION'
export const SEND_SELECTED_NOTIFICATION_SUCCESS = 'SEND_SELECTED_NOTIFICATION_SUCCESS'
export const SEND_SELECTED_NOTIFICATION_FAILED = 'SEND_SELECTED_NOTIFICATION_FAILED'

//Get Selected Notification
export const GET_SELECTED_NOTIFICATION = 'GET_SELECTED_NOTIFICATION'
export const GET_SELECTED_NOTIFICATION_SUCCESS = 'GET_SELECTED_NOTIFICATION_SUCCESS'
export const GET_SELECTED_NOTIFICATION_FAILED = 'GET_SELECTED_NOTIFICATION_FAILED'

//Get ListOF Notification
export const GET_LIST_OF_NOTIFICATION = 'GET_LIST_OF_NOTIFICATION'
export const GET_LIST_OF_NOTIFICATION_SUCCESS = 'GET_LIST_OF_NOTIFICATION_SUCCESS'
export const GET_LIST_OF_NOTIFICATION_FAILED = 'GET_LIST_OF_NOTIFICATION_FAILED'

//Remove KeepNotification Info
export const REMOVE_NOTIFICATION_INFO = 'REMOVE_NOTIFICATION_INFO'
export const REMOVE_SELECTED_NOTIFICATION = 'REMOVE_SELECTED_NOTIFICATION'
