//Podcast List
export const FETCH_PODCAST_LIST = 'FETCH_PODCAST_LIST'
export const FETCH_PODCAST_LIST_SUCCESS = 'FETCH_PODCAST_LIST_SUCCESS'
export const FETCH_PODCAST_LIST_FAILED = 'FETCH_PODCAST_LIST_FAILED'

//Podcast Node
export const FETCH_PODCAST_EPISODE = 'FETCH_PODCAST_EPISODE'
export const FETCH_PODCAST_EPISODE_SUCCESS = 'FETCH_PODCAST_EPISODE_SUCCESS'
export const FETCH_PODCAST_EPISODE_FAILED = 'FETCH_PODCAST_EPISODE_FAILED'
