export const FETCH_DMA_INTRODUCTION = 'FETCH_DMA_INTRODUCTION';
export const FETCH_DMA_INTRODUCTION_SUCCESS = 'FETCH_DMA_INTRODUCTION_SUCCESS';
export const FETCH_DMA_INTRODUCTION_ERROR = 'FETCH_DMA_INTRODUCTION_ERROR';

export const FETCH_DMA_OPTIONS_LIST = 'FETCH_DMA_OPTIONS_LIST';
export const FETCH_DMA_OPTIONS_LIST_SUCCESS = 'FETCH_DMA_OPTIONS_LIST_SUCCESS';
export const FETCH_DMA_OPTIONS_LIST_ERROR = 'FETCH_DMA_OPTIONS_LIST_ERROR';
