export const REQUEST_ARTICLE_DETAIL = 'REQUEST_ARTICLE_DETAIL'
export const REQUEST_ARTICLE_DETAIL_SUCCESS = 'REQUEST_ARTICLE_DETAIL_SUCCESS'
export const REQUEST_ARTICLE_DETAIL_FAILED = 'REQUEST_ARTICLE_DETAIL_FAILED'
