export const REQUEST_ARTICLE_DETAIL = 'REQUEST_ARTICLE_DETAIL'
export const REQUEST_ARTICLE_DETAIL_SUCCESS = 'REQUEST_ARTICLE_DETAIL_SUCCESS'
export const REQUEST_ARTICLE_DETAIL_FAILED = 'REQUEST_ARTICLE_DETAIL_FAILED'

//Related Article
export const REQUEST_RELATED_ARTICLE = 'REQUEST_RELATED_ARTICLE'
export const REQUEST_RELATED_ARTICLE_SUCCESS = 'REQUEST_RELATED_ARTICLE_SUCCESS'
export const REQUEST_RELATED_ARTICLE_FAILED = 'REQUEST_RELATED_ARTICLE_FAILED'

export const EMPTY_DATA = 'EMPTY_DATA'

//Article Section
export const REQUEST_ARTICLE_SECTION = 'REQUEST_ARTICLE_SECTION'
export const REQUEST_ARTICLE_SECTION_SUCCESS = 'REQUEST_ARTICLE_SECTION_SUCCESS'
export const REQUEST_ARTICLE_SECTION_FAILED = 'REQUEST_ARTICLE_SECTION_FAILED'

//Article RICH HTML Read Also Bundle
export const REQUEST_RICH_ARTICLE_READ_ALSO = 'REQUEST_RICH_ARTICLE_READ_ALSO'
export const REQUEST_RICH_ARTICLE_READ_ALSO_SUCCESS = 'REQUEST_RICH_ARTICLE_READ_ALSO_SUCCESS'
export const REQUEST_RICH_ARTICLE_READ_ALSO_FAILED = 'REQUEST_RICH_ARTICLE_READ_ALSO_FAILED'

//Article RICH HTML Content Bundle
export const REQUEST_RICH_ARTICLE_CONTENT = 'REQUEST_RICH_ARTICLE_CONTENT'
export const REQUEST_RICH_ARTICLE_CONTENT_SUCCESS = 'REQUEST_RICH_ARTICLE_CONTENT_SUCCESS'
export const REQUEST_RICH_ARTICLE_CONTENT_FAILED = 'REQUEST_RICH_ARTICLE_CONTENT_FAILED'

//Article RICH HTML Opinion Bundle
export const REQUEST_RICH_ARTICLE_OPINION = 'REQUEST_RICH_ARTICLE_OPINION'
export const REQUEST_RICH_ARTICLE_OPINION_SUCCESS = 'REQUEST_RICH_ARTICLE_OPINION_SUCCESS'
export const REQUEST_RICH_ARTICLE_OPINION_FAILED = 'REQUEST_RICH_ARTICLE_OPINION_FAILED'
