export const REQUEST_ARTICLE_DETAIL = 'REQUEST_ARTICLE_DETAIL'
export const REQUEST_ARTICLE_DETAIL_SUCCESS = 'REQUEST_ARTICLE_DETAIL_SUCCESS'
export const REQUEST_ARTICLE_DETAIL_FAILED = 'REQUEST_ARTICLE_DETAIL_FAILED'

//Related Article
export const REQUEST_RELATED_ARTICLE = 'REQUEST_RELATED_ARTICLE'
export const REQUEST_RELATED_ARTICLE_SUCCESS = 'REQUEST_RELATED_ARTICLE_SUCCESS'
export const REQUEST_RELATED_ARTICLE_FAILED = 'REQUEST_RELATED_ARTICLE_FAILED'

export const EMPTY_DATA = 'EMPTY_DATA'

//Article Section
export const REQUEST_ARTICLE_SECTION = 'REQUEST_ARTICLE_SECTION'
export const REQUEST_ARTICLE_SECTION_SUCCESS = 'REQUEST_ARTICLE_SECTION_SUCCESS'
export const REQUEST_ARTICLE_SECTION_FAILED = 'REQUEST_ARTICLE_SECTION_FAILED'