export const SEND_BOOK_MARK_ID = 'SEND_BOOK_MARK_ID'
export const SEND_BOOK_MARK_ID_SUCCESS = 'SEND_BOOK_MARK_ID_SUCCESS'
export const SEND_BOOK_MARK_ID_FAILED = 'SEND_BOOK_MARK_ID_FAILED'


//Get BookMark id
export const GET_BOOK_MARKED = 'GET_BOOK_MARKED'
export const GET_BOOK_MARKED_SUCCESS = 'GET_BOOK_MARKED_SUCCESS'
export const GET_BOOK_MARKED_FAILED = 'GET_BOOK_MARKED_FAILED'

//Get BookMark Detail info
export const GET_BOOK_MARKED_DETAIL_INFO = 'GET_BOOK_MARKED_DETAIL_INFO'
export const GET_BOOK_MARKED_SUCCESS_DETAIL_INFO = 'GET_BOOK_MARKED_SUCCESS_DETAIL_INFO'
export const GET_BOOK_MARKED_FAILED_DETAIL_INFO = 'GET_BOOK_MARKED_FAILED_DETAIL_INFO'
export const UPDATED_FILTERED_DATA_SUCCESS = 'UPDATED_FILTERED_DATA_SUCCESS'
export const UPDATE_ADD_REMOVE_BOOK_MARK = 'UPDATE_ADD_REMOVE_BOOK_MARK'


//Remove BookMark
export const REMOVE_BOOK_MARKED = 'REMOVE_BOOK_MARKED'
export const REMOVE_BOOK_MARKED_SUCCESS = 'REMOVE_BOOK_MARKED_SUCCESS'
export const REMOVE_BOOK_MARKED_FAILED = 'REMOVE_BOOK_MARKED_FAILED'
