export const colors = {
  black: '#000000',
  white: '#FFFFFF',
  red: '#CB3737',
  greyDark: '#333333',
  greyDark10: '#3333331A',
  greyDark50: '#33333380',
  athensGray: '#F8F9FA',
  mysticGray: '#E7EBF0',
  altoGray: '#D8D8D8',
  lightBgGray: '#F3F5F7',
  blue: '#183D69',
  blue03: '#183D6908',
  blue05: '#183D690D',
  blue10: '#183D691A',
  blue01: '#003DA5',
  blue15: '#183D6926',
  blue50: '#183D6980',
  blueCadet: '#A6B3C1',
  blueGeyser: '#DCE2E8',
  greyLight: '#999999',
  white10: '#FFFFFF1A',
  white20: '#FFFFFF33',
  greyDark20: '#33333333',
  blueOpacity5: '#183D690D',
  yellow: '#FFBA49',
  black10: '#0000001A',
  whiteTitle: '#EAEAEA',
  dim_gray: '#707070',
  aquaHaze: '#F7FAFA',
  silverChalice: '#AFAFAF',
  davyGrey: '#555555',
  smokeyGrey: '#707070',
  greenishBlue: '#2C8A82',
  transparent: 'transparent',
  lightToneGreen: '#90A3A2',
  darkSlateGray: '#253C3A',
  cyanGreen: '#ECF4F3',
  spanishGray: '#929898',
  grayNurse: '#E3EBE6',
  doveGray: '#717171',
  cyanGray: '#CED9D8',
  darkGreenishBlue: '#174038',
  codGray: '#070606',
  nightBlack: '#080808',
  onyx: '#101010',
  jasper: '#CE4242',
  mountainMist: '#929898',
  gableGreen: '#1A3333',
  lightGray: '#B1B1B1',
  whiteSmoke: '#F5F5F5',
  greyLight1:'#DCDFDF',
  darkGreenish: '#253c3a',
};

export interface CustomThemeType {
  id: string,
  primary: string,
  primaryBlack: string,
  primaryLightGray: string,
  primaryDarkSlateGray: string,
  secondaryGreen: string,
  secondaryWhite: string,
  secondaryDavyGrey: string,
  secondaryDarkSlate: string,
  secondarySpanishGray: string,
  backgroundColor: string,
  whiteSurface: string,
  danger: string,
  textColor: string,
  textInputColor: string,
  headerColor: string,
}

export const LIGHT_THEME_ID = 'light'
export const DARK_THEME_ID = 'dark'

export const DEFAULT_LIGHT_THEME: CustomThemeType = {
  id: LIGHT_THEME_ID,
  primary: colors.greenishBlue,
  primaryBlack: colors.black,
  primaryLightGray: colors.lightGray,
  primaryDarkSlateGray: colors.darkSlateGray,
  secondaryGreen: colors.cyanGreen,
  secondaryWhite: colors.white,
  secondaryDavyGrey: colors.davyGrey,
  secondaryDarkSlate: colors.darkSlateGray,
  secondarySpanishGray: colors.black,
  backgroundColor: colors.aquaHaze,
  whiteSurface: colors.white,
  danger: colors.jasper,
  textColor: colors.greyDark50,
  textInputColor: colors.black,
  headerColor: colors.darkGreenish,
}

export const DEFAULT_DARK_THEME: CustomThemeType = {
  id: DARK_THEME_ID,
  primary: colors.greenishBlue,
  primaryBlack: colors.white,
  primaryLightGray: colors.nightBlack,
  primaryDarkSlateGray: colors.white,
  secondaryGreen: colors.onyx,
  secondaryWhite: colors.nightBlack,
  secondaryDavyGrey: colors.mountainMist,
  secondaryDarkSlate: colors.white,
  secondarySpanishGray: colors.spanishGray,
  backgroundColor: colors.codGray,
  whiteSurface: colors.onyx,
  danger: colors.jasper,
  textColor: colors.white,
  textInputColor: colors.white,
  headerColor: colors.greenishBlue,
}

