export const colors = {
  black: '#000000',
  white: '#FFFFFF',
  red: '#CB3737',
  greyDark: '#333333',
  greyDark10: '#3333331A',
  greyDark50: '#33333380',
  athensGray: '#F8F9FA',
  mysticGray: '#E7EBF0',
  altoGray: '#D8D8D8',
  lightBgGray: '#F3F5F7',
  blue: '#183D69',
  blue03: '#183D6908',
  blue05: '#183D690D',
  blue10: '#183D691A',
  blue01: '#003DA5',
  blue15: '#183D6926',
  blue50: '#183D6980',
  blueCadet: '#A6B3C1',
  blueGeyser: '#DCE2E8',
  greyLight: '#999999',
  white10: '#FFFFFF1A',
  white20: '#FFFFFF33',
  greyDark20: '#33333333',
  blueOpacity5: '#183D690D',
  yellow: '#FFBA49',
  black10: '#0000001A',
  whiteTitle: '#EAEAEA',
  dim_gray: '#707070',
  aquaHaze: '#F7FAFA',
  silverChalice: '#AFAFAF',
  davyGrey: '#555555',
  smokeyGrey: '#707070',
  greenishBlue: '#2C8A82',
  transparent: 'transparent',
  lightToneGreen: '#90A3A2',
  darkSlateGray: '#253C3A',
  cyanGreen: '#ECF4F3',
  spanishGray: '#929898',
  grayNurse: '#E3EBE6',
  doveGray: '#717171',
  cyanGray: '#CED9D8',
  darkGreenishBlue: '#174038',
  codGray: '#070606',
  nightBlack: '#080808',
  onyx: '#101010',
  jasper: '#CE4242',
  mountainMist: '#929898',
  gableGreen: '#1A3333',
  lightGray: '#B1B1B1',
  whiteSmoke: '#F5F5F5',
  greyLight1:'#DCDFDF',
  darkGreenish: '#253c3a',
  greyNickel: '#C3C3C3',
  grayTransparentLightMode: '#000000E6',
  grayTransparentDarkMode: '#C8C8C81A',
  lightGreenishBlue: '#7DCEC7',
  quickSilver: '#969696',
  slateGray: '#4D4D4D',
  blackOpacity95: '#000000F2',
  gableGreenOpacity15: '#1A333326',
  nightRiderGray: '#2E2E2E',
  chineseWhite: '#E0E0E0',
  whiteTransparent: '#FFFFFFF2',
  blackTransparent: '#000000F2',
  paleRed: '#F0F0F0',
  nobelGray: '#959595',
  darkRed: '#FC2C2C',
  iceCold: '#B2F5EA',
  deepPeach: '#F8CBB1',
};

export interface CustomThemeType {
  id: string,
  primary: string,
  primaryBlack: string,
  primaryLightGray: string,
  primaryDarkSlateGray: string,
  secondaryGreen: string,
  secondaryWhite: string,
  secondaryDavyGrey: string,
  secondaryDarkSlate: string,
  secondarySpanishGray: string,
  backgroundColor: string,
  whiteSurface: string,
  danger: string,
  textColor: string,
  textInputColor: string,
  headerColor: string,
  filterBackgroundColor: string,
  filterBorderColor: string,
  secondaryMediumGrey: string,
  alertBackground: string,
  dropDownLabelColor: string,
  optionBackground: string,
  dividerColor: string,
  podcastEpisodeCardColor: string,
  miniPlayerBackgroundColor: string,
  miniPlayerBorderColor: string,
  lightRed: string,
  primaryNobel: string,
  signInTextColor: string,
  signinRightsColor: string,
  newsletterHighlighter: string,
  authorTitle: string,
  signInSeparator: string,
}

export const LIGHT_THEME_ID = 'light'
export const DARK_THEME_ID = 'dark'

export const DEFAULT_LIGHT_THEME: CustomThemeType = {
  id: LIGHT_THEME_ID,
  primary: colors.greenishBlue,
  primaryBlack: colors.black,
  primaryLightGray: colors.lightGray,
  primaryDarkSlateGray: colors.darkSlateGray,
  secondaryGreen: colors.cyanGreen,
  secondaryWhite: colors.white,
  secondaryDavyGrey: colors.davyGrey,
  secondaryDarkSlate: colors.darkSlateGray,
  secondarySpanishGray: colors.black,
  backgroundColor: colors.aquaHaze,
  whiteSurface: colors.white,
  danger: colors.jasper,
  textColor: colors.greyDark50,
  textInputColor: colors.black,
  headerColor: colors.darkGreenish,
  filterBackgroundColor: colors.black,
  filterBorderColor: colors.cyanGray,
  secondaryMediumGrey: colors.doveGray,
  alertBackground: colors.grayTransparentLightMode,
  dropDownLabelColor: colors.quickSilver,
  optionBackground: colors.aquaHaze,
  dividerColor: colors.gableGreenOpacity15,
  podcastEpisodeCardColor: colors.white,
  miniPlayerBackgroundColor: colors.whiteTransparent,
  miniPlayerBorderColor: colors.chineseWhite,
  lightRed: colors.paleRed,
  primaryNobel: colors.nobelGray,
  signInTextColor: colors.davyGrey,
  signinRightsColor: colors.spanishGray,
  newsletterHighlighter: colors.cyanGreen,
  authorTitle: colors.greenishBlue,
  signInSeparator: colors.greyLight1,
}

export const DEFAULT_DARK_THEME: CustomThemeType = {
  id: DARK_THEME_ID,
  primary: colors.greenishBlue,
  primaryBlack: colors.white,
  primaryLightGray: colors.nightBlack,
  primaryDarkSlateGray: colors.white,
  secondaryGreen: colors.onyx,
  secondaryWhite: colors.nightBlack,
  secondaryDavyGrey: colors.mountainMist,
  secondaryDarkSlate: colors.white,
  secondarySpanishGray: colors.spanishGray,
  backgroundColor: colors.codGray,
  whiteSurface: colors.onyx,
  danger: colors.jasper,
  textColor: colors.white,
  textInputColor: colors.white,
  headerColor: colors.greenishBlue,
  filterBackgroundColor: colors.greenishBlue,
  filterBorderColor: colors.greenishBlue,
  secondaryMediumGrey: colors.silverChalice,
  alertBackground: colors.grayTransparentDarkMode,
  dropDownLabelColor: colors.white,
  optionBackground: colors.slateGray,
  dividerColor: colors.nightRiderGray,
  podcastEpisodeCardColor: colors.onyx,
  miniPlayerBackgroundColor: colors.blackTransparent,
  miniPlayerBorderColor:colors.onyx,
  lightRed:colors.onyx,
  primaryNobel: colors.white,
  signInTextColor: colors.white,
  signinRightsColor: colors.white,
  newsletterHighlighter:colors.greyDark50,
  authorTitle: colors.spanishGray,
  signInSeparator: colors.white,
}

