export const FETCH_EMAIL_CHECK = 'FETCH_EMAIL_CHECK';
export const FETCH_EMAIL_CHECK_SUCCESS = 'FETCH_EMAIL_CHECK_SUCCESS';
export const FETCH_EMAIL_CHECK_ERROR = 'FETCH_EMAIL_CHECK_ERROR';
export const EMPTY_EMAIL_CHECK_DATA = 'EMPTY_EMAIL_CHECK_DATA'
