export const STORE_APP_THEME = 'STORE_APP_THEME'
export const IS_APP_FIRST_SESSION = 'IS_APP_FIRST_SESSION'
export const STORE_SERVER_ENVIRONMENT = 'STORE_SERVER_ENVIRONMENT'
export const STORE_FONT_SIZE = 'STORE_FONT_SIZE'
export const RESET_ARTICLE_FONT_SIZE = 'RESET_ARTICLE_FONT_SIZE'
export const STORE_BASE_URL_CONFIG = 'STORE_BASE_URL_CONFIG';
