export const FETCH_OPINION_WRITER = 'FETCH_OPINION_WRITER';
export const FETCH_OPINION_WRITER_SUCCESS = 'FETCH_OPINION_WRITER_SUCCESS';
export const FETCH_OPINION_WRITER_ERROR = 'FETCH_OPINION_WRITER_ERROR';
