export const SEND_CONTACT_US_INFO = 'SEND_CONTACT_US_INFO'
export const SEND_CONTACT_US_INFO_SUCCESS = 'SEND_CONTACT_US_INFO_SUCCESS'
export const SEND_CONTACT_US_INFO_FAILED = 'SEND_CONTACT_US_INFO_FAILED'

export const EMPTY_CONTACT_US_DETAIL = 'EMPTY_CONTACT_US_DETAIL'
