export const FETCH_ALBUM_LIST = 'FETCH_FAVOURITE_OPINIONS';
export const FETCH_ALBUM_LIST_SUCCESS = 'FETCH_ALBUM_LIST_SUCCESS';
export const FETCH_ALBUM_LIST_ERROR = 'FETCH_ALBUM_LIST_ERROR';
export const EMPTY_ALL_DATA = 'EMPTY_ALL_DATA';

export const FETCH_ALBUM_DETAIL = 'FETCH_ALBUM_DETAIL';
export const FETCH_ALBUM_DETAIL_SUCCESS = 'FETCH_ALBUM_DETAIL_SUCCESS';
export const FETCH_ALBUM_DETAIL_FAILED = 'FETCH_ALBUM_DETAIL_FAILED';
