//Article
export const GET_JOURNALIST_ARTICLE_INFO = 'GET_JOURNALIST_ARTICLE'
export const GET_JOURNALIST_ARTICLE_SUCCESS = 'GET_JOURNALIST_ARTICLE_SUCCESS'
export const GET_JOURNALIST_ARTICLE_FAILED = 'GET_JOURNALIST_ARTICLE_FAILED'
export const EMPTY_JOURNALIST_ARTICLE = 'EMPTY_JOURNALIST_ARTICLE'

//Detail
export const FETCH_JOURNALIST_DETAIL = 'FETCH_JOURNALIST_DETAIL';
export const FETCH_JOURNALIST_DETAIL_SUCCESS = 'FETCH_JOURNALIST_DETAIL_SUCCESS';
export const FETCH_JOURNALIST_DETAIL_ERROR = 'FETCH_JOURNALIST_DETAIL_ERROR';
export const EMPTY_JOURNALIST_DETAIL = 'EMPTY_JOURNALIST_DETAIL';
