export const REQUEST_STATIC_DETAIL = 'REQUEST_STATIC_DETAIL'
export const REQUEST_STATIC_DETAIL_SUCCESS = 'REQUEST_STATIC_DETAIL_SUCCESS'
export const REQUEST_STATIC_DETAIL_FAILED = 'REQUEST_STATIC_DETAIL_FAILED'
