export const REQUEST_OPINION_ARTICLE_DETAIL = 'REQUEST_OPINION_ARTICLE_DETAIL';
export const REQUEST_OPINION_ARTICLE_DETAIL_SUCCESS =
  'REQUEST_OPINION_ARTICLE_DETAIL_SUCCESS';
export const REQUEST_OPINION_ARTICLE_DETAIL_FAILED =
  'REQUEST_OPINION_ARTICLE_DETAIL_FAILED';
