export const REQUEST_OPINION_ARTICLE_DETAIL = 'REQUEST_OPINION_ARTICLE_DETAIL';
export const REQUEST_OPINION_ARTICLE_DETAIL_SUCCESS =
  'REQUEST_OPINION_ARTICLE_DETAIL_SUCCESS';
export const REQUEST_OPINION_ARTICLE_DETAIL_FAILED =
  'REQUEST_OPINION_ARTICLE_DETAIL_FAILED';

//Related Opinion
export const REQUEST_RELATED_OPINION = 'REQUEST_RELATED_OPINION'
export const REQUEST_RELATED_OPINION_SUCCESS = 'REQUEST_RELATED_OPINION_SUCCESS'
export const REQUEST_RELATED_OPINION_FAILED = 'REQUEST_RELATED_OPINION_FAILED'
export const EMPTY_RELATED_OPINION_DATA = 'EMPTY_RELATED_OPINION_DATA'

export const EMPTY_OPINION_ARTICLE_DETAIL = 'EMPTY_OPINION_ARTICLE_DETAIL'

//Narrated Opinion Article
export const REQUEST_NARRATED_OPINION_ARTICLE = 'REQUEST_NARRATED_OPINION_ARTICLE'
export const REQUEST_NARRATED_OPINION_ARTICLE_SUCCESS = 'REQUEST_NARRATED_OPINION_ARTICLE_SUCCESS'
export const REQUEST_NARRATED_OPINION_ARTICLE_FAILED = 'REQUEST_NARRATED_OPINION_ARTICLE_FAILED'
