export const FETCH_DOCUMENTARY_VIDEO = 'FETCH_DOCUMENTARY_VIDEO';
export const FETCH_DOCUMENTARY_VIDEO_SUCCESS = 'FETCH_DOCUMENTARY_VIDEO_SUCCESS';
export const FETCH_DOCUMENTARY_VIDEO_FAILED = 'FETCH_DOCUMENTARY_VIDEO_FAILED';
