//Get Selected News Letter
export const GET_SELECTED_NEWS_LETTERS = 'GET_SELECTED_NEWS_LETTERS';
export const GET_SELECTED_NEWS_LETTERS_SUCCESS = 'GET_SELECTED_NEWS_LETTERS_SUCCESS';
export const GET_SELECTED_NEWS_LETTERS_ERROR = 'GET_SELECTED_NEWS_LETTERS_ERROR';

//Send Selected News Letter
export const SEND_SELECTED_NEWS_LETTERS = 'SEND_SELECTED_NEWS_LETTERS';
export const SEND_SELECTED_NEWS_LETTERS_SUCCESS = 'SEND_SELECTED_NEWS_LETTERS_SUCCESS';
export const SEND_SELECTED_NEWS_LETTERS_ERROR = 'SEND_SELECTED_NEWS_LETTERS_ERROR';

//Get My News Letter
export const GET_MY_NEWS_LETTERS = 'GET_MY_NEWS_LETTERS';
export const GET_MY_NEWS_LETTERS_SUCCESS = 'GET_MY_NEWS_LETTERS_SUCCESS';
export const GET_MY_NEWS_LETTERS_ERROR = 'GET_MY_NEWS_LETTERS_ERROR';

//Empty Selected News Letter Info
export const EMPTY_SELECTED_NEWS_LETTERS_INFO = 'EMPTY_SELECTED_NEWS_LETTERS_INFO';

