export const UPDATE_PROFILE_USER_IMAGE = 'UPDATE_PROFILE_USER_IMAGE';
export const UPDATE_USER_IMAGE_SUCCESS = 'UPDATE_USER_IMAGE_SUCCESS';
export const UPDATE_USER_IMAGE_FAILED = 'UPDATE_USER_IMAGE_FAILED';
