export const GET_WEATHER_DETAILS_REQUEST = 'GET_WEATHER_DETAILS_REQUEST';
export const GET_WEATHER_DETAILS_SUCCESS = 'GET_WEATHER_DETAILS_SUCCESS';
export const GET_WEATHER_DETAILS_FAILED = 'GET_WEATHER_DETAILS_FAILED';

export const GET_WEATHER_DETAILS_VISIBILITY_REQUEST = 'GET_WEATHER_DETAILS_VISIBILITY_REQUEST';
export const GET_WEATHER_DETAILS_VISIBILITY_SUCCESS = 'GET_WEATHER_DETAILS_VISIBILITY_SUCCESS';
export const GET_WEATHER_DETAILS_VISIBILITY_FAILED = 'GET_WEATHER_DETAILS_VISIBILITY_FAILED';
