export const GET_WEATHER_DETAILS_REQUEST = 'GET_WEATHER_DETAILS_REQUEST';
export const GET_WEATHER_DETAILS_SUCCESS = 'GET_WEATHER_DETAILS_SUCCESS';
export const GET_WEATHER_DETAILS_FAILED = 'GET_WEATHER_DETAILS_FAILED';
